<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task #12</title>
    <link rel="stylesheet" type="text/css" href='css/style.css'>
</head>
<body>
    <p>12. Написать функцию, которая в качестве аргумента принимает строку, и форматирует ее таким образом, что предложения идут в обратном порядке.<br>
Пример:<br><br>
Входная строка:  'А Васька слушает да ест. А воз и ныне там. А вы друзья как ни садитесь, все в музыканты не годитесь. А король-то — голый. А ларчик просто открывался. А там хоть трава не расти.';<br><br>
Строка, возвращенная функцией :  'А там хоть трава не расти. А ларчик просто открывался. А король-то — голый. А вы друзья как ни садитесь, все в музыканты не годитесь. А воз и ныне там. А Васька слушает да ест.'</p>
    <b><?=$msg?></b>
    <form class = 'inputForm inputFormMinHeight0' method='post'>
        <div class = 'form-row'>
            Input text:<textarea name="inputText"></textarea>
        </div>
        <div class = 'form-row'>
            <input type="submit" value="Go">
        </div>
    </form>

    <hr>
    <h3>Result text: <?=$res?></h3>

</body>
</html>