<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task #07</title>
    <link rel="stylesheet" type="text/css" href='css/style.css'>
</head>
<body>
    <p>7. Создать гостевую книгу, где любой человек может оставить комментарий в текстовом поле и добавить его. Все добавленные комментарии выводятся над текстовым полем.</p>
    <b><?=$msg?></b>
    <h3>Messages:</h3>
    <table>
        <?php foreach ($allMessages as $value): ?>
            <tr><td><?=$value?></td></tr>
        <?php endforeach ?>
    </table>
    <hr>

    <form class = 'inputForm' method = 'post'>
        <div class = 'form-row'>
            Input comment:<textarea name="message"></textarea>
        </div>
        <div class = 'form-row'>
            <input type = 'submit' value = "Add">
        </div>
    </form>

</body>
</html>