<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task #11</title>
    <link rel="stylesheet" type="text/css" href='css/style.css'>
</head>
<body>
    <p>11. Написать функцию, которая в качестве аргумента принимает строку, и форматирует ее таким образом, что каждое новое предложение начиняется с большой буквы.<br>
Пример:<br>
Входная строка: 'а васька слушает да ест. а воз и ныне там. а вы друзья как ни садитесь, все в музыканты не годитесь. а король-то — голый. а ларчик просто открывался. а там хоть трава не расти.';<br><br>
Строка, возвращенная функцией :  'А Васька слушает да ест. А воз и ныне там. А вы друзья как ни садитесь, все в музыканты не годитесь. А король-то — голый. А ларчик просто открывался. А там хоть трава не расти.';</p>
    <b><?=$msg?></b>
    <form class = 'inputForm inputFormMinHeight0' method='post'>
        <div class = 'form-row'>
            Input text:<textarea name="inputText"></textarea>
        </div>
        <div class = 'form-row'>
            <input type="submit" value="Go">
        </div>
    </form>

    <hr>
    <h3>Result text: <?=$res?></h3>

</body>
</html>