<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Books mini site</title>
</head>
<body>
    
    <div class='menu'>
        <a href="/books_minisite/index.php?controller=books&amp;action=list">Books</a>   
        <a href="/books_minisite/index.php?controller=feedback">Feedback messages</a>   
        <a href="/books_minisite/index.php?controller=security">Logout</a>
    </div>
    <hr>
    
    <div class='content'>
        <b><?=get_Flash('message', '')?></b><br>
        <?=$content ?>
        
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
    
    <div class='footer'>
        some footer
    </div>
    
</body>
</html>